#!/bin/sh
#PBS -N start_ignite
#PBS -r n
#PBS -q batch 

cd $PBS_O_WORKDIR

igniteHome=`python readJsonField.py configuration.json igniteHome`                          # Ignite home path
configIgniteFilePath=`python readJsonField.py configuration.json configIgniteFilePath`      # Ignite configuration XML file path

export IGNITE_HOME=$igniteHome

bash "$igniteHome/bin/ignite.sh" $configIgniteFilePath

